name: Duplicate code bonus

on: [ pull_request ]

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "."
          ignore_below: 5
          file_extensions: "java"
          fail_above: 70
          warn_above: 30

