name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport

      - name: Debug: List Build Directory
        run: ls -R sonarqube/sonar-application/build/distributions/

      - name: Extract SonarQube ZIP
        run: |
          ZIP_FILE="sonarqube/sonar-application/build/distributions/sonar-application-25.2-SNAPSHOT.zip"
          if [ -f "$ZIP_FILE" ]; then
            unzip "$ZIP_FILE" -d sonarqube/sonar-application/build/distributions/
          else
            echo "ERROR: ZIP file not found! Check Gradle build output."
            exit 1
          fi

      - name: Start SonarQube
        run: |
          chmod +x sonarqube/sonar-application/build/distributions/sonar-application-25.2-SNAPSHOT/bin/linux-x86-64/sonar.sh
          sonarqube/sonar-application/build/distributions/sonar-application-25.2-SNAPSHOT/bin/linux-x86-64/sonar.sh start
